### ISSUE TITLE
Download dump file for homebridge-deconz and homebridge-hue2

### ISSUE THREAD

**Issue by ebaauw** [homebridge/homebridge-config-ui-x#1268]
**Is your feature request related to a problem? Please describe:**

I'm finally migrating homebridge-hue to dynamic platform accessories.  Rather than updating the plugin, forcing a big-bang migration, I'm actually creating two new plugins: homebridge-deconz and homebridge-hue2, see https://github.com/ebaauw/homebridge-hue/issues/1070.  Both new plugins will be creating a dump file, just like homebridge-hue.

**Describe the solution you'd like:**

Same feature as #676 for homebridge-hue: an option to download the dump file from the plugin _Settings_ in the UI.

The dump files will be named: `homebridge-deconz.json.gz` and `homebridge-hue2.json.gz`.

**Describe alternatives you've considered:**

None.  If it ain't broke...

**Additional context:**

Since the new plugins can now persist data in `cachedAccessories`, there's no longer a need to add the API key (username) to config.json.  Consequently, I'm also getting rid of the user-defined keys in config.json.

I'm still in the process of developing the new plugins, and they're not yet creating the dump files, so there's no hurry to implement this.  Just filing the issue already, so you can do this at a moment that's convenient for you.  As always, thanks!

**Comment by ebaauw** [comment]
I'm actually trying to create a dynamic settings interface, using @homebride/plugin-ui-utils.  Maybe I could create the option to download the dump file there?

How do I create a button on the form that looks like the DOWNLOAD button?  Or like the SAVE?  I managed to create a button alright, but I cannot make it black or purple - only ugly white, red, or blue.

I do see an error in Safari's JavaScript console, but I don't think it causes any ill effects:
 ```
Error while parsing the 'sandbox' attribute: 'allow-downloads' is an invalid sandbox flag.
setAttribute — main-es2015.9d482d945810494ac85a.js:1:291804
setAttribute — main-es2015.9d482d945810494ac85a.js:1:2287626
Tt — main-es2015.9d482d945810494ac85a.js:1:128272
mo — main-es2015.9d482d945810494ac85a.js:1:172260
bo — main-es2015.9d482d945810494ac85a.js:1:172892
template — main-es2015.9d482d945810494ac85a.js:1:2150553
$i — main-es2015.9d482d945810494ac85a.js:1:156161
qi — main-es2015.9d482d945810494ac85a.js:1:154357
fn — main-es2015.9d482d945810494ac85a.js:1:162256
(anonymous function) — main-es2015.9d482d945810494ac85a.js:1:154558
qi — main-es2015.9d482d945810494ac85a.js:1:154567
create — main-es2015.9d482d945810494ac85a.js:1:215566
_createFromComponent — main-es2015.9d482d945810494ac85a.js:1:423435
open — main-es2015.9d482d945810494ac85a.js:1:421622
(anonymous function) — main-es2015.9d482d945810494ac85a.js:1:2152794
generatorResume
o — main-es2015.9d482d945810494ac85a.js:1:2491729
onInvoke — main-es2015.9d482d945810494ac85a.js:1:229053
run — polyfills-es2015.e8bb8be2ebc926cac2d0.js:1:1916
(anonymous function) — polyfills-es2015.e8bb8be2ebc926cac2d0.js:1:16689
onInvokeTask — main-es2015.9d482d945810494ac85a.js:1:228873
runTask — polyfills-es2015.e8bb8be2ebc926cac2d0.js:1:2535
m — polyfills-es2015.e8bb8be2ebc926cac2d0.js:1:9130
invokeTask — polyfills-es2015.e8bb8be2ebc926cac2d0.js:1:8209
p — polyfills-es2015.e8bb8be2ebc926cac2d0.js:1:20146
f — polyfills-es2015.e8bb8be2ebc926cac2d0.js:1:20465
setAttribute — main-es2015.9d482d945810494ac85a.js:1:291804
```

**Comment by bwp91** [comment]
hi erik just going through some of the issues here, did this come to a resolution?

**Comment by ebaauw** [comment]
Not yet.  Homebridge deCONZ is now on v1.x and fully functional, except for the dynamic settings interface.  I’m more into backends and not really experienced in UI development (that’s why I’m using Homebridge in the first place: to let HomeKit handle the UI).

I looked into creating a PR for homebridge-config-ui-x, but had a hard time understanding the code.
