### ISSUE TITLE
Attempting to upgrade NodeJS

### ISSUE THREAD

**Issue by Subivan1** [homebridge/homebridge-config-ui-x#1474]
### Current Situation

 I have made a number of attempts to update nodes from 18:13 to 18:15. Every time I end up unable to restart homebridge and having to remove and reinstall.

I am running on a Pi 4 using homebridge 1.6.0
node version 18.13.0
I have run hb-service update-node from the terminal within the main gui and also by using vnc to a terminal on the I and running sudo hb-service update-node

In both circumstances everything appears to be going well, no error messages or problems indicated then when I restart homebridge, nothing happens and I cannot access config-ui in anyway. Ultimate solution is to remove homebridge, reinstall and restore backup back to 18:13

Am I doing something wrong?

### Logs

```text
None of the logs I know how to access show 
anything other than showing services stopping then restore process.
```

### Homebridge UI Version

5.50.2

### Homebridge Version

1.6.0

### Node.js Version

18.13.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bjornand1** [comment]
Not exactly the same issue, but I am afraid I have made a terrible mistake with Node.js. I am running Homebridge on a Synology and the package center on the DSM said there was an update to Node.js, which I installed (to 18.12). That messed up Homebridge, which won't start now. I tried using to terminal to "sudo hb-service update-node" but that fails.

I really hope there is a way to fix this?

**Comment by pponce** [comment]
I have the same issue.
I was not sure if this is an issue with the apt homebridge package, the homebridge image or homebridge.
I posted this bug report in the homebridge image project. It has more detail.
https://github.com/homebridge/homebridge-raspbian-image/issues/106

When I install to my rpi4b the latest homebridge image. Restore from backup, then update to latest homebridge package via 
`sudo apt-get install homebridge`
Then
`sudo hb-service update-node`

My homebridge then refuses to start.

**Comment by Subivan1** [comment]
still unable to update after numerous attempts including totally fresh install on a new sd disk.
these are the only messages I see when updating

Log 

Updating Node.js from v18.13.0 to v18.15.0...
ℹ Target: /opt/homebridge
✔ Download complete.
✔ Cleaned up npm at at /opt/homebridge/lib/node_modules/npm
✔ Installed Node.js v18.15.0
⚠ Please restart Homebridge for the changes to take effect.

Restarting Homebridge
 sudo hb-service start
Starting Homebridge... restart is taking a long time. You may need to bring up the Homebridge service manually.
Restart Command Executed: End Process
Homebridge UI Online
Homebridge Server Ready



sudo hb-service start
Starting Homebridge...

**Comment by Biggsylad** [comment]
Same problem, new install and cannot get UI to load following Node update

**Comment by Subivan1** [comment]
Cross posting the https://github.com/homebridge/homebridge/issues/3349#issuecomment-1523832510 for the issue.
Also with temp workaround provided.

**Comment by Subivan1** [comment]
Many Thanks to everyone who solved this.
Cross posting the https://github.com/homebridge/homebridge/issues/3349#issuecomment-1523832510 for the issue.
Also with temp workaround provided.
