### ISSUE TITLE
Missing /api/server/qrcode.svg after upgrade to v4.50.2

### ISSUE THREAD

**Issue by rtrauer** [homebridge/homebridge-config-ui-x#1476]
### Feature Description

After upgrading homebridge-config-ui-x from version v4.41.2 to v4.50.2 the qr-code link is not available anymore.
Has the link changed or is this feature missing ?
I still can get the pairing code number from /api/server/pairing
But don´t know how to convert that into a qr-code link.

Homebridge system is running on
OS: Linux 4.14.52 arm ( Ubuntu 16.04.7 LTS 4.14.52 )
Node.js v16.19.0

Thanks for your attention.

**Comment by NorthernMan54** [comment]
Have you tried to 'Reset Layout' ?

<img width="1086" alt="image" src="https://github.com/homebridge/homebridge-config-ui-x/assets/19808920/315d37f0-124c-4902-a34f-ead406744c25">
