### ISSUE TITLE
"1 Plugins Out Of Date"

### ISSUE THREAD

**Issue by epheterson** [homebridge/homebridge-config-ui-x#1478]
### Describe The Bug

See screenshot, when only one plugin needs an update the plurality of "plugins" is incorrect. Small issue, but would be nice if it correctly said "1 plugin" or "2 plugins".

<img width="243" alt="Screenshot 2023-04-12 at 5 55 29 PM" src="https://user-images.githubusercontent.com/151483/231618232-c5afe1ee-621c-4642-841a-3e2dc5d5026d.png">

### Homebridge UI Version

homebridge-config-ui-x v4.50.2

### Homebridge Version

v1.6.0

### Node.js Version

v15.10.0

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by epheterson** [comment]
Bump

**Comment by NorthernMan54** [comment]
Is the fix for this #1458?

**Comment by epheterson** [comment]
Sure looks like it to me!

**Comment by donavanbecker** [comment]
@epheterson Should be in the latest beta
