### ISSUE TITLE
Node 20 Support

### ISSUE THREAD

**Issue by jmnovak50** [homebridge/homebridge-config-ui-x#1480]
### Current Situation

Hi!

Seeing Nodejs is finally out of the 19 branch and now into 20.  Is there a plan to support it?  If so, is there a general timeline?

Thank you so much in providing any information you might have. :)

### Homebridge UI Version

4.50.2

### Homebridge Version

1.6

### Node.js Version

18.16

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
Hi,

I have just updated the wiki about versions that Homebridge supports including v20:
https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

Please bear in mind that just because it is not officially supported does not mean it wont work. I have been running node 20 on my system for a few days now without any issue!

If you _do_ decide to update to node 20 and encounter any issues, it could be helpful for any plugin dev to know about this - but does not _necessarily_ mean that they are 'expected' to fix until homebridge itself officially supports node 20 - from October 2023 when it goes into active lts:
https://nodejs.dev/en/about/releases/

**Comment by jmnovak50** [comment]
Thank you @bwp91.  This is helpful.  I'm certainly trying to help, however, new to node and HB and I wish I was as fortunate.  For some reason, I keep getting erroring on hb-service update-node, with some unusual errors.  When I try back with 18.16.0 it seems to work.  Any thoughts?

[5/5/2023, 7:27:22 AM] [HB Supervisor] UI Path: /var/lib/homebridge/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /var/lib/homebridge/node_modules/.pnpm/node-pty-prebuilt-multiarch@0.10.1-pre.5/node_modules/node-pty-prebuilt-multiarch/lib/prebuild-loader.js
- /var/lib/homebridge/node_modules/.pnpm/node-pty-prebuilt-multiarch@0.10.1-pre.5/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /var/lib/homebridge/node_modules/.pnpm/node-pty-prebuilt-multiarch@0.10.1-pre.5/node_modules/node-pty-prebuilt-multiarch/lib/index.js
- /var/lib/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.50.2/node_modules/homebridge-config-ui-x/dist/main.js
- /var/lib/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.50.2/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Module._load (node:internal/modules/cjs/loader:928:27)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/node-pty-prebuilt-multiarch@0.10.1-pre.5/node_modules/node-pty-prebuilt-multiarch/lib/prebuild-loader.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Module.require (node:internal/modules/cjs/loader:1149:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/lib/homebridge/node_modules/.pnpm/node-pty-prebuilt-multiarch@0.10.1-pre.5/node_modules/node-pty-prebuilt-multiarch/lib/prebuild-loader.js',
    '/var/lib/homebridge/node_modules/.pnpm/node-pty-prebuilt-multiarch@0.10.1-pre.5/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js',
    '/var/lib/homebridge/node_modules/.pnpm/node-pty-prebuilt-multiarch@0.10.1-pre.5/node_modules/node-pty-prebuilt-multiarch/lib/index.js',
    '/var/lib/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.50.2/node_modules/homebridge-config-ui-x/dist/main.js',
    '/var/lib/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.50.2/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}

Any help would be greatly appreciate!

Best Regards,

Jason

**Comment by bwp91** [comment]
Hi @jmnovak50 

can you try updating to the test version of the homebridge ui -> https://github.com/homebridge/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

and then trying to update your node version to 20?

**Comment by jmnovak50** [comment]
Hi Ben,

The test version seemed to correct these issues.  Thank you so much!  I will leave open for you to determine whether this should be closed or not.

Best Regards,

Jason

**Comment by NorthernMan54** [comment]
Release 4.51.0 includes Node 20 support
