### ISSUE TITLE
Logs enhancements

### ISSUE THREAD

**Issue by mkz212** [homebridge/homebridge-config-ui-x#1488]
### Feature Description

1. Extending the log recording time to a minimum of 24 hours. Or even an option to choose the time: 1 day, 7 days, 30 days. 

2. Saving each day in a separate file. 

3. Log filtering option: 
- Accessory: all, one or more
- Plugin: all, one or more
- Log type: all, normal logs, error logs
- date range: current activity or from date and time to date and time.

**Comment by zsolthy** [comment]
My biggest problem with logging is that it truncates the log file when it reaches the size of 1MB (!!!) (see private async truncateLog() method in src/bin/hb-service.ts file).

**Comment by mkz212** [comment]
I don't know if it's because there are some restrictions or if it has a purpose? But I know that I would like to have a text file with the log from each day separately. Or at least longer log period (minimum 24h, preffered even 7 or 30 days).
