### ISSUE TITLE
Last update does not appear in the dashboard

### ISSUE THREAD

**Issue by masterfordev** [homebridge/homebridge-config-ui-x#1491]
### Describe The Bug

Last update does not appear in the dashboard.
I think it is because you changed the URLs of the repository.

### Homebridge UI Version

4.50.2

### Homebridge Version

1.6.1

### Node.js Version

18.16.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by fate8383** [comment]
yeah does not show

**Comment by NorthernMan54** [comment]
The issue is the automated publishing is not working yet, give us a few more hours.

https://github.com/homebridge/homebridge-config-ui-x/commits/beta-4.50.4

**Comment by NorthernMan54** [comment]
And the release was published a few minutes ago.  Still have a minor issue with the release workflow version numbering as the published version number on npm is 4.50.3, while GitHub is 4.50.4.  And the change log is not displaying correctly.

Will resolve these with the next release.
