### ISSUE TITLE
Backlog for Release 4.50.5

### ISSUE THREAD

**Issue by NorthernMan54** [homebridge/homebridge-config-ui-x#1494]
### Feature Description

Release Workflow

* Change the trigger for `Attach Artifacts` to be the successful completion of the `Node Release` workflow.  How to - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
* Is it possible to augment `release.yml` to check that the release tag and package.json are in alignment, or have package,json be updated to match the release tag.
* Can we add other other housekeeping pre-checks to release.yml including CHANGELOG.md ?

UI
* removing depricated releases from showing in the install alternate Version drop down. I deprecated 4.50.3 on NPM, but it still shows in the dropdown.

Dependant Packages - Validate and automate

* https://github.com/homebridge/homebridge-raspbian-image
* https://github.com/homebridge/docker-homebridge
* https://github.com/homebridge/homebridge-apt-pkg
* https://github.com/homebridge/homebridge-syno-spk
* https://github.com/homebridge/homebridge-vm-image
* https://github.com/homebridge/homebridge-macos-pkg

**Comment by NorthernMan54** [comment]
Not stale

**Comment by jsiegenthaler** [comment]
Bump. Unstale.

**Comment by donavanbecker** [comment]
> Bump. Unstale.

Not needed, this has been pined. Also your last comment before this should be a separate issue
