### ISSUE TITLE
Cannot update to 4.50.4 

### ISSUE THREAD

**Issue by nebosphere19** [homebridge/homebridge-config-ui-x#1495]
### Describe The Bug

Bundle update fails, then it tries via npm command, which also fails.

### Logs

```text
Bundled update failed. Trying regular update using npm.

USER: barons
DIR: /usr/local
CMD: npm install -g homebridge-config-ui-x@4.50.4

npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/@fastify%2fhelmet reason: Invalid response body while trying to fetch https://registry.npmjs.org/@fastify%2fhelmet: EACCES: permission denied, open '/Users/barons/.npm/_cacache/index-v5/5d/f2/5c15c9d4520bd1f9f29f13953266b87a8cc3902699230dedb81a7838898f'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/barons/.npm/_logs/2023-05-15T01_17_27_790Z-debug-0.log

Cleaning up npm cache, please wait...
npm cache cleared, please try updating homebridge-config-ui-x again.

Operation failed. Please review log for details.
```

### Homebridge UI Version

4.50.3

### Homebridge Version

1.6.1

### Node.js Version

16.20.0

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Looking at the log, it appears that you have a permission issue with the directory /Users/barons/.npm/_cacache

EACCES: permission denied, open '/Users/barons/.npm/_cacache/index-v5/5d/f2/5c15c9d4520bd1f9f29f13953266b87a8cc3902699230dedb81a7838898f

**Comment by nebosphere19** [comment]
ok - do you know what the permissions should be on that dir? Everything looks consistent, but maybe it's consistently wrong? It's all drwxr-xr-x   barons  staff

**Comment by nebosphere19** [comment]
when I try to run it from the command line using sudo I get:

barons-mac-pro:index-v5 barons$ sudo npm install -g homebridge-config-ui-x@4.50.4
Password:
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/process reason: Invalid response body while trying to fetch https://registry.npmjs.org/process: ENOENT: no such file or directory, stat '/Users/barons/.npm/_cacache/content-v2/sha512/09/cf/4b35c8ee3a615fe482711fcf942d6830a18ef9a2d8da83ade789f0f8257311fb3ac37000547d48f36a751667b105de0d7b3e59559d2b691d1fd738291c6e'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/barons/.npm/_logs/2023-05-16T01_18_56_319Z-debug-0.log
barons-mac-pro:index-v5 barons$

**Comment by nebosphere19** [comment]
ok - I think resolved by running npm audit fix first. I was able to install via the command line. npm still says I have a bunch of package problems but they won't fix because too many dependencies. Afraid to force it....

**Comment by NorthernMan54** [comment]
Glad to hear that you resolved it.
