### ISSUE TITLE
hb-status reports wrong port when multiple instances

### ISSUE THREAD

**Issue by TeslaOwnerTips** [homebridge/homebridge-config-ui-x#1498]
### Describe The Bug

When multiple instances of homebridge are running (I had a specific reason to do this.) 
hb-service status; hb-service --service-name=homebridge2 status; hb-service --service-name=homebridge4 status; hb-service --service-name=homebridge5 status

ℹ Testing hb-service is running on port 8581...
✔ Homebridge UI Running
ℹ Testing hb-service is running on port 8581...
✔ Homebridge UI Running
ℹ Testing hb-service is running on port 8581...
✔ Homebridge UI Running
ℹ Testing hb-service is running on port 8581...
✔ Homebridge UI Running

The actual ports are
51793, 51956, 51362, 51369

### Homebridge UI Version

homebridge-config-ui-x v4.50.4

### Homebridge Version

 Homebridge v1.6.1 (HAP v0.11.1) (Mac Mini) 

### Node.js Version

Node.js v18.16.0

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by TeslaOwnerTips** [comment]
hb-service install --service-name homebridge --port 8081
sudo hb-service uninstall --service-name homebridge6 --port 8582
sudo hb-service install --service-name homebridge2 --port 8582
sudo hb-service install --service-name homebridge3 --port 8583
sudo hb-service install --service-name homebridge4 --port 8584
sudo hb-service install --service-name homebridge5 --port 8585

**Comment by NorthernMan54** [comment]
@TeslaOwnerTips If you look at the source behind hb-service you can see that the status command checks for the homebridge UI and not individual instances.   So the behaviour is as per design
