### ISSUE TITLE
CLI list all instances

### ISSUE THREAD

**Issue by TeslaOwnerTips** [homebridge/homebridge-config-ui-x#1500]
### Feature Description

hb-service list

This would list all the instances and child bridges

Mac-mini:~ $ ps -xo command | grep homebridge | sort -u | grep -v grep
homebridge      
homebridge: @milo526/homebridge-tuya-web     
homebridge: homebridge-bond     
homebridge: homebridge-camera-ffmpeg     
homebridge: homebridge-http-webhooks     
homebridge: homebridge-messenger     
homebridge: homebridge-rpi     
homebridge: homebridge-tcc     
homebridge: homebridge-tplink-smarthome     
homebridge: homebridge-weather-plus

**Comment by NorthernMan54** [comment]
A pull request with the feature would be accepted
