### ISSUE TITLE
Websocket API usage ?

### ISSUE THREAD

**Issue by fred-ast** [homebridge/homebridge-config-ui-x#1505]
### Current Situation

Hi,

I m looking for Websocket API documentation.

I already found the embedded documentation through my local server with swagger but only HTTP endpoint are listed.

I introspected web-ui network call and it seems this ui only use websocket.

I tried couple of action (auth / accessories-list / accessories action) with API and it works fine, no worry. But it also appears websocket is a better way for building an app, in order to have a nice async result of using accessory. 

Thank you 😊

### Homebridge UI Version

Latest

### Homebridge Version

Latest

### Node.js Version

18

### Operating System

Synology DSM

### Environment Info

- [X] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by NorsonNack** [comment]
> ### Current Situation
> 
> Hi,
> 
> 
> 
> I m looking for Websocket API documentation.
> 
> 
> 
> I already found the embedded documentation through my local server with swagger but only HTTP endpoint are listed.
> 
> 
> 
> I introspected web-ui network call and it seems this ui only use websocket.
> 
> 
> 
> I tried couple of action (auth / accessories-list / accessories action) with API and it works fine, no worry. But it also appears websocket is a better way for building an app, in order to have a nice async result of using accessory. 
> 
> 
> 
> Thank you 😊
> 
> ### Logs
> 
> _No response_
> 
> ### Config
> 
> _No response_
> 
> ### Homebridge UI Version
> 
> Latest
> 
> ### Homebridge Version
> 
> Latest
> 
> ### Node.js Version
> 
> 18
> 
> ### Operating System
> 
> Synology DSM
> 
> ### Environment Info
> 
> - [X] Using Docker?
> - [ ] Using Hyper-V?
> - [X] Using hb-service?
> 
> ### Raspberry Pi Model
> 
> None

**Comment by NorthernMan54** [comment]
@fred-ast Personally to find the API, I would need to review the source code.  The client and the server side are all within this code base.  The WS server is here - https://github.com/homebridge/homebridge-config-ui-x/blob/master/src/modules/accessories/accessories.service.ts

**Comment by fred-ast** [comment]
I did not take time yet to investigate, but sure I’ ll do.
I close this question.
