### ISSUE TITLE
I am sharing '13fd7dd6-4043-4660-b491-04f1c5f28690' with you

### ISSUE THREAD

**Issue by damiengolden3674** [homebridge/homebridge-config-ui-x#1508]
![13fd7dd6-4043-4660-b491-04f1c5f28690.jpeg](https://github.com/homebridge/homebridge-config-ui-x/assets/138087321/0a721d03-442c-4193-a400-ee07cce1c5df)

**Comment by NorthernMan54** [comment]
I'm not sure I understand what this is about
