### ISSUE TITLE
Macosx CPU Temperature

### ISSUE THREAD

**Issue by bubez81** [homebridge/homebridge-config-ui-x#1512]
### Describe The Bug

Hello! I can't figure out why I don't see the cpu temperature on macosx, yet the System Information library also supports macosx. Are there any special steps that I need to perform by any chance?

### Config

```json
"name": "Config",
            "tempUnits": "c",
            "lang": "it",
            "port": 8581,
            "theme": "dark-mode-green",
            "auth": "form",
            "platform": "config",
            "accessoryControl": {
                "instanceBlacklist": [
                    "CC:17:9D:E3:DE:54"
                ]
            }
```

### Homebridge UI Version

V4.50.4

### Homebridge Version

V1.6.1

### Node.js Version

v18.17.0

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by bubez81** [comment]
Nothing?

**Comment by NorthernMan54** [comment]
The library we use to collect system temperature doesn't support MacOS without an additional package.  Please read this

https://github.com/sebhildebrandt/systeminformation#known-issues

**Comment by bubez81** [comment]
npm install osx-temperature-sensor --save works! Thank you!!

**Comment by donavanbecker** [comment]
@bubez81 Please open a PR, with changes.

**Comment by bubez81** [comment]
I can't I'm not a contributor
