### ISSUE TITLE
Keep receiving EHOSTUNREACH errors with several plugins

### ISSUE THREAD

**Issue by jamesj1390** [homebridge/homebridge-config-ui-x#1519]
### Current Situation

HI all, I'm about at my wits end. I've been using Homebridge for several months with only a few user-created hiccups. Within the last few days, I keep receiving this repetative error:
[Ring] Failed to reach Ring server at [https://api.ring.com/clients_api/ring_devices](https://l.facebook.com/l.php?u=https%3A%2F%2Fapi.ring.com%2Fclients_api%2Fring_devices%3Ffbclid%3DIwAR3O2epsPwnNATc4S4jzxPNdksK_6DSh-jTSNJgqexB9uUjJS45UEu70lyg&h=AT0KDLKlUGQ3R3Wnd1lqS8J6o1iInJ3kJGB3XZnhc7pLpNNqBtjgl80tU2pQKmsFgHaLzmIWRWbSE9p6hkvPx-iIVrfArEh2Cu4Yaq9NzQr_-0hwaQmaBGvDl0CrHfKkXfK-wbZkpV_juawnXw9k0b0_OA&__tn__=-UK-R&c[0]=AT1qx-ETheDl8yHwbKmKPPIIqtnFwxcl2LRQ-lc8vzfAn7-Oga6ct-IhYVtDoq6Na0qLQg7Be_fKIIqXg6jMHNY2fUyKvvSKrmUXhXxao23BB_GjPqCBA4H1mtD_iulDrFW-H0fBjUNrJwXxSN8daqIzbiCzilaC) connect EHOSTUNREACH 15.197.187.26:443.  Trying again in 5 seconds...
This believe this is indicative of Homebridge not being able to access the internet. I'm not sure what's changed on my network or my host computer (MacOS). I have IPv6 disabled on my router and am not running Eeros (was but am no longer due to a host of other issues). I'm having this issue across the board with Ring, MyQ, Tuya, and the Levoit plug-ins. I've tried installing fresh instances on both my Mac Mini, which is the normal host, and my MacBook Air as a way to test.

The log above is from when I was trying to get the Ring plugin to work again. The log below is from when I was trying to get the MyQ plugin to work. 

### Logs

```text
Setup Payload:
X-HM://0024U81WX06JD
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 827-90-833 │     
    └────────────┘     
                       
[8/5/2023, 12:06:57 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 4166) is running on port 51763.
[8/5/2023, 12:06:58 PM] [myQ] Launched child bridge with PID 28062
[8/5/2023, 12:06:58 PM] Registering platform 'homebridge-myq.myQ'
[8/5/2023, 12:06:58 PM] [myQ] Loaded homebridge-myq v2.12.0 child bridge successfully
[8/5/2023, 12:06:58 PM] Loaded 1 cached accessories from cachedAccessories.0E9A7822685A.
[8/5/2023, 12:06:58 PM] Homebridge v1.6.1 (HAP v0.11.1) (myQ) is running on port 37916.
[8/5/2023, 12:06:59 PM] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "connect EHOSTUNREACH 104.16.2.35:443" - see https://homebridge.io/w/JJSz6 for help.
[8/5/2023, 12:07:04 PM] [myQ] connect EHOSTUNREACH 40.71.237.110:443
[8/5/2023, 12:07:04 PM] [myQ] myQ API: Unable to access the OAuth authorization endpoint.
[8/5/2023, 12:09:02 PM] [myQ] myQ API: Successfully connected to the myQ API.
[8/5/2023, 12:09:02 PM] [myQ] connect EHOSTUNREACH 40.71.237.168:443
[8/5/2023, 12:09:02 PM] [myQ] myQ API: Unable to retrieve account information.
[8/5/2023, 12:11:03 PM] [myQ] connect EHOSTUNREACH 40.71.237.110:443
[8/5/2023, 12:11:03 PM] [myQ] myQ API: Unable to complete the OAuth login redirect.
```

### Config

```json
{
    "bridge": {
        "name": "Homebridge 4166",
        "username": "0E:F4:DE:39:41:66",
        "port": 51763,
        "pin": "827-90-833",
        "advertiser": "ciao",
        "bind": [
            "en0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "email": "xxxxxxxx",
            "password": "xxxxxxx",
            "name": "myQ",
            "platform": "myQ",
            "_bridge": {
                "username": "0E:9A:78:22:68:5A",
                "port": 37916
            }
        }
    ]
}
```

### Homebridge UI Version

4.50.4

### Homebridge Version

1.6.1

### Node.js Version

18.17.0

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by adrianradtke** [comment]
I have the same issue described above

**Comment by bwp91** [comment]
Hi @jamesj1390 did you managed to get your issue sorted in the end?

**Comment by apple-ihack-geek** [comment]
Not sure why this was marked as "Awaiting user reply", when there aren't any questions here for the user, but I have the same issue since updating to the version of macOS this user probably did.  I think it's because node doesn't have access to discover things on the local network. I don't know  a workaround yet...

**Comment by NorthernMan54** [comment]
Did you try this?

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS#macos-150--sequoia

**Comment by apple-ihack-geek** [comment]
thank you @NorthernMan54 , that does appear to be the exact issue.  The only issue their solution, to reinstall node (brew reinstall node) doesn't make node appear in the list, and I'm not sure how to proceed next...
