### ISSUE TITLE
Settings Rendering Issues of Plugins Not Working Properly

### ISSUE THREAD

**Issue by simplytoast1** [homebridge/homebridge-config-ui-x#1527]
### Describe The Bug

I have a content blocker on my machines (StopTheMadness) and have found in 4.50.5 settings for Homebridge MyQ no longer show.  This bug does not exist in 4.50.4.  Issue exists in any version of Homebridge MyQ on 4.50.5.

Disabling StopTheMadness or running in private browsing renders the page correctly.  Also a rollback to 4.50.4 solves the issues as well.

### Logs

```text
No logging errors - just UI glitches.
```

### Config

```json
n/a
```

### Homebridge UI Version

4.50.5

### Homebridge Version

1.6.1

### Node.js Version

18.17.1

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
@dnicolson, any thoughts? seems like this might be from changes in [homebridge/plugin-ui-utils](https://github.com/homebridge/plugin-ui-utils).

**Comment by simplytoast1** [comment]
Sure... Find Movies attached...

This is normal behavior before 4.50.5 and all content blockers disabled.  (Video taken using 4.50.4 and content blockers on)
https://drive.google.com/file/d/1v_qIu4RE8Q7u8e2PZ9tN6rK-FzK4lWPz/view?usp=drive_link

This is the behavior on on 4.50.5 with content blockers on
https://drive.google.com/file/d/1EL09yBfA6Q4LkaS_uf5LAHIJ8OtA292S/view?usp=drive_link

**Comment by dnicolson** [comment]
It looks like a JavaScript error or a JavaScript network request is blocked.

Do you see anything in the DevTools/Web Inspector console or any blocked requests in the network tab?

**Comment by simplytoast1** [comment]
Yes, on the 4.50.5 release I get a JavaScript error: Error while parsing the 'sandbox' attribute: 'allow-downloads' is an invalid sandbox flag.

This error is not generated on 4.50.4

**Comment by dnicolson** [comment]
That's odd because that error is apparently benign and also that attribute hasn't been changed in years:
https://github.com/homebridge/homebridge-config-ui-x/blame/b81fa60a2c2c5bc56a940f2426e914cad7df7cea/ui/src/app/core/manage-plugins/custom-plugins/custom-plugins.component.html#L16

Was anything blocked in the network tab? Do you see different results in different browsers?

**Comment by simplytoast1** [comment]
There is nothing being blocked.. But in 4.50.5 I also get an error in the console log.

[Error] Did not parse stylesheet at 'http://xxx.xxx.xxx.xxx:8080/webkit-masked-url://hidden/' because non CSS MIME types are not allowed in strict mode.

This does not happen in 4.50.4

**Comment by donavanbecker** [comment]
@dnicolson Thoughts on what would cause this with the changes you made?

**Comment by dnicolson** [comment]
Nothing comes to mind, I see that some of the changes are reverted in the beta branch. Can you get @simplytoast1 to test releases with the changes reverted?

**Comment by donavanbecker** [comment]
I reverted but then reverted that revert.

**Comment by donavanbecker** [comment]
I wonder if it is a dependency?

**Comment by dnicolson** [comment]
It could be. The issue doesn't appear to be reproducible so creating betas with incremental changes might be the only way forward.

**Comment by donavanbecker** [comment]
reverted to @homebridge/plugin-ui-utils@0.0.19, @simplytoast1 once the next beta is released can you test it out so we can see if this is related to changes done on that repo?

**Comment by bwp91** [comment]
Any updates on this? @simplytoast1

**Comment by simplytoast1** [comment]
The issue is still occurring in 1.6.2b0

**Comment by maximuswallis** [comment]
Hi. I'm having the same problem with the settings of Homebridge UniFi Protect. The settings do not show up when I click settings. I first noticed it on Chrome IOS and have also had the same problem on Chrome on MacOS. Switching to incognito fixes the problem. I also managed to access the settings through Safari. I noticed that if I downgrade below HBUP V6.13, the problem goes away and comes back if I update to HBUP V13 and up. I also tried downgrading HBUI from 4.50.6 all the way down to 4.43.1 but it made no change. Hope this helps.

**Comment by bwp91** [comment]
Hi @maximuswallis 

Just tried a combination myself of latest macos (14.0), chrome (117.0.5938.149), unifi-protect (6.15.1) and homebridge-ui (most recent beta).

Although I don't have devices for this plugin, I downloaded it out of interest and the settings screen loads for me with no issue.

Are you still having trouble with this? Could you try updating to the most recent beta of the Homebridge UI to check if you still get the issue?
- https://github.com/homebridge/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by dnicolson** [comment]
@bwp91 or @donavanbecker can you please release a new beta that includes https://github.com/homebridge/plugin-ui-utils/pull/14?

Thanks!

**Comment by donavanbecker** [comment]
@dnicolson Will do

**Comment by donavanbecker** [comment]
@dnicolson 4.50.7-test.18 should have changes.

**Comment by jarz** [comment]
Just encountered this issue on _one_ computer but not another. Here's what's logged when loading the settings page for homebridge-myq (`http://host:8581/api/plugins/settings-ui/homebridge-myq/index.html?origin=http%3A%2F%2Fhost%3A8581&v=3.4.3`):

> Refused to apply style from 'http://host:8581/chrome-extension://hokifickgkhplphjiodbggjmoafhignh/fonts/fabric-icons.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

`hokifickgkhplphjiodbggjmoafhignh` is _Microsoft Editor: Spelling & Grammar Checker_ ([Edge Add-ons](https://microsoftedge.microsoft.com/addons/detail/microsoft-editor-spellin/hokifickgkhplphjiodbggjmoafhignh)).

Here's a [gist](https://gist.github.com/jarz/46d5accc0ec76317c6e6654b3520dfe6) with the iframe content. The beginning of line 17 includes two places where the extension creates a bad href.

**Comment by donavanbecker** [comment]
@jarz have you tried the latest beta of Homebridge UI?

**Comment by jarz** [comment]
Thanks for the pointer @donavanbecker -- the beta release fixes it.

**Comment by maximuswallis** [comment]
> Hi @maximuswallis
> 
> Just tried a combination myself of latest macos (14.0), chrome (117.0.5938.149), unifi-protect (6.15.1) and homebridge-ui (most recent beta).
> 
> Although I don't have devices for this plugin, I downloaded it out of interest and the settings screen loads for me with no issue.
> 
> Are you still having trouble with this? Could you try updating to the most recent beta of the Homebridge UI to check if you still get the issue?
> 
> * https://github.com/homebridge/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

Hi, I tried updating to the latest beta '4.51.0-test.2' and also 'v4.50.7-test.18', but unfortunately neither fixed the problem for me. Wish I had better news for you! (By the way, I am running Mac OS Catalina - not sure if that is relevant but throwing it out there since you mentioned you are running Sonoma)

**Comment by bwp91** [comment]
Is this still an issue? on the most recent beta version of the UI?

**Comment by bwp91** [comment]
Closing due to no response
