### ISSUE TITLE
Update accessory name in Config-UI-X

### ISSUE THREAD

**Issue by tillkruss** [homebridge/homebridge-config-ui-x#1528]
### Current Situation

What is the correct API to update the `displayName` of a `PlatformAccessory`, so it's reflected in Config-UI-X?

<img width="860" alt="Screenshot 2023-08-24 at 12 52 01 PM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/665029/87102bed-28e9-45f1-8f26-99319ff340f2">

### Homebridge UI Version

v4.50.5

### Homebridge Version

v1.6.1

### Node.js Version

v20.5.1

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Have you tried the Configured Name Characteristic ?

**Comment by tillkruss** [comment]
I did not, thanks!
