### ISSUE TITLE
Accessories Disappearing From ConfigUI Accessories Tab But Continue Working In Home App

### ISSUE THREAD

**Issue by iSteve-O** [homebridge/homebridge-config-ui-x#1529]
### Describe The Bug

My homebridge on raspi4 is operating normally, but sometimes when I go to the accessories tab a bunch of my accessories have gone missing. They all still work in the home app when not visible & restarting their plugin's child bridge will make them reappear, if only temporarily, but this can also cause others to disappear. It is not causing any functional issue. 

The only thing I can think of is I have too many. I have 9 platforms including configUI, all on their own child bridges, and there are 54 "devices" in the accessories tab when everything is showing. The pi idles around 3-6% CPU & 35-40% memory, so it seems to have enough resources. 

This only started happening recently, and my first thought was maybe I need a new SD card, but everything else is working fine. It probably coincided with the last or next to last UI update. 

### Logs

```text
No relevant logs
```

### Config

```json
Not relevant but available upon request.
```

### Homebridge UI Version

4.50.5

### Homebridge Version

1.6.1

### Node.js Version

18.17.1

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [x] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by cheetah3k5** [comment]
I have the same issue. It happened before, it fixed itself after a few weeks, now it started doing it again
Homebridge UI Version: 4.50.5
Homebridge Version: 1.6.1
Node.js Version: 18.17.1
NPM Version: 9.6.7
Operating System: Docker

**Comment by bwp91** [comment]
This may not be the solution for everyone, but check out this wiki article re running in insecure mode:

https://github.com/homebridge/homebridge-config-ui-x/wiki/Enabling-Accessory-Control

**Comment by iSteve-O** [comment]
This is still happening.

**Comment by cheetah3k5** [comment]
Even though it's not the best solution and as bwp01 suggested before with his take on the problem, it is not for everyone, I have added the plugs in Samsung's SmartThings app and use SmartThings Plugin on homebridge to control the plugs. This means, of course, that every plug is accesed through Samsung's API over the internet

**Comment by cheetah3k5** [comment]
I have found that reseting the container, then updating nodejs and homebridge ui fixes the problem

**Comment by iSteve-O** [comment]
> I have found that reseting the container, then updating nodejs and homebridge ui fixes the problem

I am not running Homebridge in a container. Reinstalling node or homebridge does not solve the issue for me. I can restart the child bridges and their devices may reappear but then others will disappear. Functionally, everything is fine since the disappeared devices still work in the home app even when they don’t appear in the accessories tab. 

My SD card was going bad, so I thought maybe that had something to do with it, but I just replaced the SD card with a brand new one and this is still happening. 

It’s not causing any real problems with functionality, it’s just an annoying glitch in the display of accessories in the UI.
