### ISSUE TITLE
container location log file

### ISSUE THREAD

**Issue by pierrotori** [homebridge/homebridge-config-ui-x#1534]
### Current Situation

i try to redirect the homebridge.log file in another directory 
i put in the docker compose
    volumes:
      - /home/pi/homebridge:/homebridge
      - /var/log:/homebridge/logs
     
and the  config.json
"log": {
		"method": "file",
		"path": "/home/pi/homebridge/logs/homebridge.log"
	}

and the log file is always in the  /home/pi/homebridge
do you have a idea ?

### Config

```json
on raspberry 2
--Software Homebridge bash--
version : v4.50.4
npm version : 9.5.1
Node version : v18.16.0
```

### Homebridge UI Version

v4.50.4

### Homebridge Version

v4.50.4

### Node.js Version

v18.16.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [X] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 2

**Comment by NorthernMan54** [comment]
docker-homebridge puts the logs into the `WorkingDirectory` that is set by systemd during startup.  This directory also contains the homebridge configuration information.  So if it is changed, everything needs to move.


Take a look at `/usr/lib/systemd/system/homebridge.service`

**Comment by pierrotori** [comment]
the homebridge work on rpi with sd card and i would like send  log on the tmpfs directory
i cat the homebridge .service, perhaps file , can i  add a landscape variable for the log ?
`[Unit]
Description=Homebridge
Wants=network-online.target
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
SupplementaryGroups=homebridge
PermissionsStartOnly=true
WorkingDirectory=/var/lib/homebridge
ExecStartPre=-/bin/run-parts /etc/hb-service/homebridge/prestart.d
ExecStart=/opt/homebridge/start.sh
Restart=always
RestartSec=3
KillMode=process
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_NET_ADMIN

[Install]
WantedBy=multi-user.target
`

**Comment by NorthernMan54** [comment]
Changing WorkingDirectory to a tmpfs will break homebridge, as the configuration is stored there as well.

Why do you want to move the log location ?   Good quality SD Cards last a long time these days.  I have several RPI homebridge setups that have been running for years on the same card.

**Comment by pierrotori** [comment]
i prefere mount in RAM the log file
there is no solution to separate the log of data  in the homebridge settings ?
in my side i create a link to homebridge.log in the var/log directory but doesn't run.

**Comment by pierrotori** [comment]
hello, no possible to add a landscape variable ?
