### ISSUE TITLE
Node update

### ISSUE THREAD

**Issue by Rikezzz** [homebridge/homebridge-config-ui-x#1536]
### Current Situation

When I try to update node.js as explained, it asks for a password but it won't let me write anything and none of my passwords work.

Please help-me

### Logs

```text
homebridge@orangepizero:/var/lib/homebridge$ sudo hb-service update-node

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for homebridge: 
Sorry, try again.
[sudo] password for homebridge: 
Sorry, try again.
[sudo] password for homebridge: 
sudo: 3 incorrect password attempts
```

### Homebridge UI Version

v1.6.1

### Homebridge Version

v4.50.6-test.4

### Node.js Version

14.16.1

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Duplicate #1538
