### ISSUE TITLE
Node.Js Update

### ISSUE THREAD

**Issue by Rikezzz** [homebridge/homebridge-config-ui-x#1538]
### Current Situation

When I try to update node.js as explained, it asks for a password but it won't let me write anything and none of my passwords work.

Please help-me

### Logs

```text
homebridge@orangepizero:/var/lib/homebridge$ sudo hb-service update-node

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for homebridge: 
Sorry, try again.
[sudo] password for homebridge: 
Sorry, try again.
[sudo] password for homebridge: 
sudo: 3 incorrect password attempts
```

### Homebridge UI Version

v4.50.6-test.4

### Homebridge Version

v1.6.1

### Node.js Version

14.16.1

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Duplicate https://github.com/homebridge/homebridge-config-ui-x/issues/1538

**Comment by NorthernMan54** [comment]
Please don't create multiple duplicate issues across multiple repositories.  It gets painful to cleanup afterwards.

When you tried this, didn't you receive this message ?

`ERROR: sudo / root access is not allowed by the homebridge service account. You can use "su <username>" to swap to your local user account. `

Please `su` to your local admin account and try again

**Comment by Rikezzz** [comment]
No I received this:

homebridge@orangepizero:/var/lib/homebridge$ sudo hb-service update-node

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for homebridge: 
Sorry, try again.
[sudo] password for homebridge: 
Sorry, try again.
[sudo] password for homebridge: 
sudo: 3 incorrect password attempts

**Comment by NorthernMan54** [comment]
You need to su to your local admin account and try again

**Comment by Rikezzz** [comment]
Solved, thank you
